collections:
  publishers:
    output: true
    permalink: "/:title"
  plugins:
    output: true
    custom_permalink_placeholders: ["publisher"]
    permalink: "/:publisher/:title"

defaults:
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugin"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - 'jekyll-sitemap'
  - 'jekyll-feed'
  - 'jekyll-seo-tag'
  - 'jekyll-mentions'
  - 'jekyll_custom_permalink'
